apiVersion: v1
kind: Service
metadata:
  name: racky-app
  namespace: {{ .Values.environment }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: frontend
    port: 5173
    protocol: TCP
    targetPort: 5173
  - name: backend
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: racky-app
  sessionAffinity: None
  type: NodePort